#  Nike Sales Data

##### This dataset contant data on retail and online sales transactions from Nike, one of the world's leading sportswear and footwear brands. records containing: Multiple product lines (Running, Basketball, Lifestyle, Training, Soccer),Gender-specific sales (Men, Women, Kids),Sales from both Retail Stores and Online Channels.

###  Column Descriptions

| Column | Description |
|--------|------------|
| Order_ID | Transaction/order ID .|
| Gender_Category | Customer segment: Men, Women, or Kids. |
| Product_Line | Product type: Running, Basketball, etc. |
| Product_Name | Specific product sold (e.g., Air Force 1, Pegasus Turbo).|
| Size|  Product size (e.g., 7, M, L,..etc).  |
| Units_Sold|  Quantity sold.  |
| MRP| Maximum retail price . |
| Discount_Applied| Discount applied on sale|
| Revenue| Final amount after discount. |
| Order_Date| Date of transaction.|
| Sales_Channel| Online or Retail. |
| Region| Indian cities.|
| Profit| Profit made .|

In [1]:
#inclued packages
import numpy as np
import pandas as pd
import plotly.express as  px 
import os

## Data Display and Checkup

In [2]:
#read Data
df=pd.read_csv("./Data/Nike_Sales_Uncleaned.csv")
df.head().sort_values('Order_ID')

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89

In [3]:
#Check data Inforamtions
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   str
 2   Product_Line      2500 non-null   str
 3   Product_Name      2500 non-null   str
 4   Size              1990 non-null   str
 5   Units_Sold        1265 non-null   float64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   str
 10  Sales_Channel     2500 non-null   str
 11  Region            2500 non-null   str
 12  Profit            2500 non-null   float64
dtypes: float64(5), int64(1), str(7)
memory usage: 362.2 KB

In [4]:
df.describe()

,Order_ID,Units_Sold,MRP,Discount_Applied,Revenue,Profit
count,2500.000000,1265.000000,1246.000000,832.000000,2500.000000,2500.000000
mean,3194.352400,1.482213,6039.863395,0.631022,274.873716,1376.012848
std,749.972638,1.696947,2315.746826,0.365500,2023.773550,1478.671013
min,2000.000000,-1.000000,2006.630000,0.000000,-7561.590000,-1199.450000
25%,2534.750000,0.000000,4038.902500,0.320000,0.000000,93.532500
50%,3192.500000,2.000000,6110.030000,0.615000,0.000000,1371.385000
75%,3841.250000,3.000000,8022.187500,0.962500,0.000000,2660.645000
max,4499.000000,4.000000,9996.220000,1.250000,37169.350000,3999.210000

In [5]:
df.describe(include='object')

C:\Users\user\AppData\Local\Temp\ipykernel_12792\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Gender_Category,Product_Line,Product_Name,Size,Order_Date,Sales_Channel,Region
count,2500,2500,2500,1990,1884,2500,2500
unique,3,5,20,10,1008,2,9
top,Kids,Training,SuperRep Go,L,17-11-2024,Online,Delhi
freq,841,546,148,513,6,1255,438

In [6]:
#Checking for data Dimensions
df.shape

(2500, 13)

In [7]:
#Categorical and Numerical columns
numerical_cols = ['Order_ID','Units_Sold','MRP','Discount_Applied','Revenue','Profit']
categorical_cols = [ 'Sales_Channel','Gender_Category', 'Product_Line', 'Product_Name', 'Size','Region']
date= ['Order_Date']

In [8]:
#Checking catogorical data
for col in categorical_cols:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*50)

Sales_Channel
2
<ArrowStringArray>
['Online', 'Retail']
Length: 2, dtype: str
 **************************************************
Gender_Category
3
<ArrowStringArray>
['Kids', 'Women', 'Men']
Length: 3, dtype: str
 **************************************************
Product_Line
5
<ArrowStringArray>
['Training', 'Soccer', 'Lifestyle', 'Running', 'Basketball']
Length: 5, dtype: str
 **************************************************
Product_Name
20
<ArrowStringArray>
[       'SuperRep Go',      'Tiempo Legend',        'Premier III',
         'Blazer Mid',     'React Infinity',       'Flex Trainer',
 'Mercurial Superfly',         'Waffle One',         'Air Jordan',
           'Metcon 7',           'Air Zoom',            'Free RN',
      'Kyrie Flytrap',         'Zoom Freak',   'ZoomX Invincible',
         'Phantom GT',      'Pegasus Turbo',           'Dunk Low',
        'Air Force 1',          'LeBron 20']
Length: 20, dtype: str
 **************************************************
Size
10
<ArrowStringArray>
['M', 'L', 'XL', '11', nan, '9', '6', '12', '7', '10', '8']
Length: 11, dtype: str
 **************************************************
Region
9
<ArrowStringArray>
['bengaluru',       'Hyd',    'Mumbai',      'Pune',     'Delhi', 'Bangalore',
 'Hyderabad',  'hyderbad',   'Kolkata']
Length: 9, dtype: str
 **************************************************

In [9]:
#Checking Numerical data
for col in numerical_cols:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*50)

Order_ID
2386
[2000 2001 2002 ... 4497 4498 4499]
 **************************************************
Units_Sold
6
[nan  3.  4.  1. -1.  0.  2.]
 **************************************************
MRP
1244
[    nan 4957.93 9673.57 ... 9009.71 6647.6  5358.7 ]
 **************************************************
Discount_Applied
126
[0.47  nan 0.32 0.86 0.3  1.17 0.67 0.66 0.5  0.16 0.22 1.05 0.82 1.07
 0.38 1.01 0.83 0.63 0.77 1.04 0.57 0.37 0.94 0.78 0.49 0.85 0.21 0.45
 0.6  1.13 0.29 0.69 0.27 0.42 1.14 0.53 0.41 1.24 0.24 0.74 0.95 1.1
 1.12 0.48 0.09 0.8  0.01 1.06 1.2  1.16 0.59 0.9  0.51 0.65 0.97 0.36
 0.11 0.12 0.31 0.89 0.84 0.39 0.54 1.08 1.03 0.07 1.22 0.26 0.25 0.81
 0.08 0.71 0.56 0.06 0.91 0.93 1.23 0.34 0.05 0.35 0.88 1.02 1.25 1.19
 0.2  0.03 1.11 0.14 0.15 1.15 0.1  0.79 0.04 0.19 0.62 1.09 0.33 0.18
 0.75 0.99 0.55 0.72 0.76 0.7  0.44 1.18 0.43 1.21 0.73 1.   0.02 0.68
 0.96 0.23 0.98 0.61 0.28 0.58 0.46 0.17 0.87 0.13 0.52 0.4  0.92 0.64
 0.  ]
 **************************************************
Revenue
167
[    0.    6910.22 -2409.48  2514.99  -169.59  1118.93  8190.84 12010.21
  5499.82  1488.65  4735.44  3445.74 16022.36  6900.2    475.14 15837.
 -2970.77  -690.82 25079.88 -1799.14  4178.88  5869.97  9158.23 -6492.08
  3969.91  -290.08 -1553.23  4231.46 17864.46 -2810.35   425.13  -634.04
 13285.66  7127.85  8505.19  3528.68  3761.39  5590.58 -5679.23  4403.21
  5815.15  8687.88  2305.23  -655.2   7864.9   9580.88  8031.86  7953.88
  -233.85   -75.04  3277.55  3544.81  -628.07 -1059.58  2929.95  2094.91
  3256.07  2766.83 18824.63 -1028.7  10003.12  -635.22 -3545.18  7953.1
   393.59 -2120.88  4612.57  8982.51  5593.   -1766.44  8781.29  1852.75
  3745.62 -4088.34  6066.79  -233.42  2445.59 -2525.97   236.32  3593.01
 -1909.29  2323.9  13528.26 -1971.78  3759.41  2323.84  8095.35  3005.74
 -4587.99 15379.41  9260.68 -1396.27 -7561.59 12412.9   1400.14  1179.3
  4418.41  2175.91  6498.22  2681.84  -998.81  3739.85  -109.28 -3467.83
  4166.9   -193.9  13007.38 37169.35 14539.45  2120.5  -3878.37  9152.81
  7281.3   6828.72 14283.55  -558.9   7026.48 10224.99 10665.6  20716.55
 -3875.68  3966.72 10312.68   157.68  3751.17 26105.37  2930.83   420.
  8318.58 -1506.9  -3389.09 10488.01 21586.98  1452.57 12844.15 10261.03
 -2328.1   -865.55  3959.56  6666.68  4483.43  -838.79  -643.57 -2391.98
  -369.33  -524.17   733.   -1197.4   1161.18   482.47  8783.1  -6479.72
 -4013.04 -2960.09  6257.1   4530.7  22459.88   596.76  3391.12 -3727.64
 -5010.39  5205.44  4995.81 -2158.22  9981.04 -2370.08  3589.15]
 **************************************************
Profit
2494
[-770.45 -112.53 3337.34 ... -918.14 3352.29 2453.57]
 **************************************************

In [10]:
#Checking for duplicates
df.duplicated().sum()

np.int64(0)

In [11]:
#Checking primary key duplicates
df['Order_ID'].duplicated().sum()

np.int64(114)

In [12]:
#Checking for missing values
df.isnull().sum().sort_values(ascending=False)

Discount_Applied    1668
MRP                 1254
Units_Sold          1235
Order_Date           616
Size                 510
Product_Name           0
Product_Line           0
Gender_Category        0
Order_ID               0
Revenue                0
Sales_Channel          0
Region                 0
Profit                 0
dtype: int64

In [13]:
# Check to Drop columns with missing value persentage >50%
null_percentage = (df.isnull().mean().sort_values(ascending=False)) * 100
print("Missing values (%):\n", null_percentage)

Missing values (%):
 Discount_Applied    66.72
MRP                 50.16
Units_Sold          49.40
Order_Date          24.64
Size                20.40
Product_Name         0.00
Product_Line         0.00
Gender_Category      0.00
Order_ID             0.00
Revenue              0.00
Sales_Channel        0.00
Region               0.00
Profit               0.00
dtype: float64

In [14]:
# Checking in regions
df['Region'].unique()

<ArrowStringArray>
['bengaluru',       'Hyd',    'Mumbai',      'Pune',     'Delhi', 'Bangalore',
 'Hyderabad',  'hyderbad',   'Kolkata']
Length: 9, dtype: str

In [15]:
# Checking Order Date
df['Order_Date']

0       2024-03-09
1       2024-07-09
2              NaN
3       04-10-2024
4       2024/09/12
           ...
2495    2025-05-14
2496           NaN
2497    02-07-2025
2498    11-12-2024
2499    23-11-2024
Name: Order_Date, Length: 2500, dtype: str

## Data Cleaning

In [16]:
# Drop columns with missing value persentage >50%
Drop=['MRP','Discount_Applied']
df=df.drop(columns=Drop)

In [17]:
 # Drop  key duplicates
df = df.drop_duplicates(subset="Order_ID", keep="first")

In [18]:
#  Order_Date Modifications

# Function to convert  Order_Date data type and deal with different date formats
def parse_date(x):
    df['Order_Date'] = df['Order_Date'].astype(str).str.strip()
    if pd.isna(x):
        return np.nan
    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%Y/%m/%d"):
        try:
            return pd.to_datetime(x, format=fmt)
        except ValueError:
            continue
    return pd.to_datetime(x, errors="coerce")

# Calling the function
df["Order_Date"] = df["Order_Date"].apply(parse_date)

#filling missing Date
df = df.sort_values(by=['Order_ID','Order_Date'], ascending=True)
df["Order_Date"] = df["Order_Date"].bfill()

# Extracting the month name
df['Month_Name'] = df['Order_Date'].dt.month_name()

# Extracting the year
df['Year'] = pd.to_numeric(df['Order_Date'].dt.year).astype(int)

# Extracting the day of the week
df['Day_Type'] = df['Order_Date'].dt.weekday.apply(
    lambda x: 'Weekend' if x >= 5 else 'Working Day'
)
df['Year_Quarter'] = df['Order_Date'].dt.quarter
df.head()

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,Revenue,Order_Date,Sales_Channel,Region,Profit,Month_Name,Year,Day_Type,Year_Quarter
0,2000,Kids,Training,SuperRep Go,M,NaN,0.0,2024-03-09,Online,bengaluru,-770.45,March,2024,Weekend,1
1,2001,Women,Soccer,Tiempo Legend,M,3.0,0.0,2024-07-09,Retail,Hyd,-112.53,July,2024,Working Day,3
2,2002,Women,Soccer,Premier III,M,4.0,0.0,2024-10-04,Retail,Mumbai,3337.34,October,2024,Working Day,4
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,0.0,2024-10-04,Online,Pune,3376.85,October,2024,Working Day,4
4,2004,Kids,Running,React Infinity,XL,NaN,0.0,2024-09-12,Retail,Delhi,187.89,September,2024,Working Day,3

In [19]:
# Correcting the regions
correct_region = {
    'bengaluru': 'Bangalore',
    'hyderbadc': 'Hyderabad',
    'hyderbad':'Hyderabad',
     'Hyd':'Hyderabad'
}
df['Region'] = df['Region'].replace(correct_region)
df['Region'].unique()

<ArrowStringArray>
['Bangalore', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Kolkata']
Length: 6, dtype: str

In [ ]:
# Size distribution detection to fill nulls
px.histogram(df, x='Size')

In [21]:
# Correcting the sizes replace nulls with Unkown based on histogram
#Use Unkown to replace nulls
df['Size'] = df["Size"].fillna('Unknown')
df['Size'] = df['Size'].astype(str).str.upper().str.strip()
df['Size'].unique()

<ArrowStringArray>
['M', 'L', 'XL', '11', 'UNKNOWN', '9', '6', '12', '7', '10', '8']
Length: 11, dtype: str

In [22]:
# Cleaning Units_Sold,revenue and profit by remove negative
df['Units_Sold'] = pd.to_numeric(df['Units_Sold'], errors='coerce').astype('Int64')
df.loc[df['Units_Sold'] <= 0, 'Units_Sold'] = abs(df['Units_Sold'])
df.loc[df['Revenue'] <= 0, 'Revenue'] = abs(df['Revenue'])
df.loc[df['Profit'] <= 0, 'Profit'] = abs(df['Profit'])

In [23]:
#First outliers Check to fill Units_Sold
px.box(df, x='Units_Sold')

In [24]:
#Second outliers check to fill Units_Sold
def outlier_percentage(series):
    series = series.dropna()
    
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = series[(series < lower_bound) | (series > upper_bound)]
    
    return round(len(outliers) / len(series) * 100, 2)
outlier_report = {
    col: outlier_percentage(df['Units_Sold'])
}

outlier_report

{'Profit': 0.0}

In [25]:
# cleaning Units_Sold fill with Median
df['Units_Sold'] = df['Units_Sold'].fillna(df['Units_Sold'].mean().round(0) )

In [26]:
#Checking Revenue = 0
zero_revenue_count = (df['Revenue'] == 0).sum()
total_count = len(df)
percentage_zero_revenue = (zero_revenue_count / total_count) * 100
print(f"Percentage of Revenue = 0: {percentage_zero_revenue:.2f}%")

Percentage of Revenue = 0: 93.34%

In [27]:
# final check
df.isnull().sum()

Order_ID           0
Gender_Category    0
Product_Line       0
Product_Name       0
Size               0
Units_Sold         0
Revenue            0
Order_Date         0
Sales_Channel      0
Region             0
Profit             0
Month_Name         0
Year               0
Day_Type           0
Year_Quarter       0
dtype: int64

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 2386 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2386 non-null   int64
 1   Gender_Category  2386 non-null   str
 2   Product_Line     2386 non-null   str
 3   Product_Name     2386 non-null   str
 4   Size             2386 non-null   str
 5   Units_Sold       2386 non-null   Int64
 6   Revenue          2386 non-null   float64
 7   Order_Date       2386 non-null   datetime64[us]
 8   Sales_Channel    2386 non-null   str
 9   Region           2386 non-null   str
 10  Profit           2386 non-null   float64
 11  Month_Name       2386 non-null   str
 12  Year             2386 non-null   int64
 13  Day_Type         2386 non-null   str
 14  Year_Quarter     2386 non-null   int32
dtypes: Int64(1), datetime64[us](1), float64(2), int32(1), int64(2), str(8)
memory usage: 483.7 KB

In [29]:
cleaned_df = df
cleaned_df.to_csv("Cleaned_Data.csv", index=False)

In [30]:
df2=pd.read_csv("Cleaned_Data.csv")
df2.head()

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,Revenue,Order_Date,Sales_Channel,Region,Profit,Month_Name,Year,Day_Type,Year_Quarter
0,2000,Kids,Training,SuperRep Go,M,2,0.0,2024-03-09,Online,Bangalore,770.45,March,2024,Weekend,1
1,2001,Women,Soccer,Tiempo Legend,M,3,0.0,2024-07-09,Retail,Hyderabad,112.53,July,2024,Working Day,3
2,2002,Women,Soccer,Premier III,M,4,0.0,2024-10-04,Retail,Mumbai,3337.34,October,2024,Working Day,4
3,2003,Kids,Lifestyle,Blazer Mid,L,2,0.0,2024-10-04,Online,Pune,3376.85,October,2024,Working Day,4
4,2004,Kids,Running,React Infinity,XL,2,0.0,2024-09-12,Retail,Delhi,187.89,September,2024,Working Day,3

In [31]:
#Define Categorical and Numerical columns
numerical_cols = ['Order_ID','Units_Sold','Revenue','Profit']
categorical_cols = [ 'Sales_Channel','Gender_Category', 'Product_Line', 'Product_Name', 'Size','Region']
date= ['Order_Date']
target = ['Profit']

In [32]:
# Numerical columns data types final check
df[numerical_cols ].dtypes

Order_ID        int64
Units_Sold      Int64
Revenue       float64
Profit        float64
dtype: object

In [33]:
# Categorical columns data types final check
df[categorical_cols ].dtypes

Sales_Channel      str
Gender_Category    str
Product_Line       str
Product_Name       str
Size               str
Region             str
dtype: object

In [34]:
#Numerical data
for col in numerical_cols:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

Order_ID
2386
[2000 2001 2002 ... 4497 4498 4499]
 ****************************************************************************************************
Units_Sold
5
<IntegerArray>
[2, 3, 4, 1, 0]
Length: 5, dtype: Int64
 ****************************************************************************************************
Revenue
160
[    0.    6910.22  2409.48  2514.99   169.59  8190.84 12010.21  5499.82
  1488.65  4735.44  3445.74 16022.36  6900.2    475.14 15837.    2970.77
 25079.88  1799.14  4178.88  5869.97  9158.23  6492.08  3969.91   290.08
  1553.23  4231.46 17864.46  2810.35   425.13   634.04  7127.85  8505.19
  3528.68  3761.39  5590.58  5679.23  4403.21  5815.15  8687.88  2305.23
   655.2   7864.9   9580.88  8031.86  7953.88   233.85    75.04  3277.55
  3544.81  1059.58  2929.95  2094.91  3256.07  2766.83 18824.63  1028.7
 10003.12   635.22  3545.18  7953.1    393.59  2120.88  4612.57  8982.51
  5593.    1766.44  8781.29  1852.75  3745.62  4088.34  6066.79   233.42
  2445.59  2525.97   236.32  3593.01  1909.29  2323.9  13528.26  1971.78
  3759.41  2323.84  8095.35  3005.74  4587.99 15379.41  9260.68  1396.27
  7561.59 12412.9   1400.14  4418.41  2175.91  6498.22  2681.84   998.81
  3739.85   109.28  3467.83  4166.9    193.9  13007.38 37169.35 14539.45
  2120.5   3878.37  9152.81  7281.3   6828.72 14283.55   558.9   7026.48
 10224.99 10665.6  20716.55  3875.68  3966.72 10312.68   157.68  3751.17
 26105.37  2930.83   420.    8318.58  1506.9  10488.01 21586.98  1452.57
 12844.15 10261.03  2328.1    865.55  3959.56  6666.68  4483.43   838.79
   643.57  2391.98   369.33   524.17   733.    1197.4   1161.18   482.47
  8783.1   6479.72  4013.04  2960.09  6257.1   4530.7  22459.88   596.76
  3391.12  3727.64  5010.39  5205.44  4995.81  9981.04  2370.08  3589.15]
 ****************************************************************************************************
Profit
2378
[ 770.45  112.53 3337.34 ...  918.14 3352.29 2453.57]
 ****************************************************************************************************

In [35]:
#Categorical data
for col in categorical_cols:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

Sales_Channel
2
<ArrowStringArray>
['Online', 'Retail']
Length: 2, dtype: str
 ****************************************************************************************************
Gender_Category
3
<ArrowStringArray>
['Kids', 'Women', 'Men']
Length: 3, dtype: str
 ****************************************************************************************************
Product_Line
5
<ArrowStringArray>
['Training', 'Soccer', 'Lifestyle', 'Running', 'Basketball']
Length: 5, dtype: str
 ****************************************************************************************************
Product_Name
20
<ArrowStringArray>
[       'SuperRep Go',      'Tiempo Legend',        'Premier III',
         'Blazer Mid',     'React Infinity',       'Flex Trainer',
 'Mercurial Superfly',         'Waffle One',         'Phantom GT',
         'Air Jordan',           'Air Zoom',            'Free RN',
      'Kyrie Flytrap',         'Zoom Freak',   'ZoomX Invincible',
           'Metcon 7',      'Pegasus Turbo',           'Dunk Low',
        'Air Force 1',          'LeBron 20']
Length: 20, dtype: str
 ****************************************************************************************************
Size
11
<ArrowStringArray>
['M', 'L', 'XL', '11', 'UNKNOWN', '9', '6', '12', '7', '10', '8']
Length: 11, dtype: str
 ****************************************************************************************************
Region
6
<ArrowStringArray>
['Bangalore', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Kolkata']
Length: 6, dtype: str
 ****************************************************************************************************

In [36]:
# Target variable
target = "Profit"

# Features
X = df.drop(columns=[target])
y = df[target]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (2386, 14)
Target shape: (2386,)

## Exploratory Data Analysis (EDA)

In [37]:
#Categorical columns data distrbution
for col in categorical_cols:
    fig=px.histogram(df,x=col,title=f'distrbution of {col}')
    fig.show()

In [38]:
#Revenue distribution
px.histogram(df, x='Revenue')

In [39]:
#Profit check
px.histogram(df, x='Profit')

In [40]:
# Profit by year
df_time = df2.groupby(df2['Year'] )['Profit'].sum().reset_index()
df_time['Year'] = df_time['Year'].astype(str)
pivot=pd.pivot_table(df2,values='Profit',index='Year', aggfunc='sum')
fig = px.bar(df_time,x="Year",y="Profit",text="Profit",title="Total Profit by Year")


# Show data
print(pivot)
fig.show()

          Profit
Year
2023   267949.93
2024  1879962.83
2025  1788801.22

In [41]:
# Profit trend
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
sales_trend = df.groupby(df['Order_Date'].dt.to_period("M"))['Profit'].sum().reset_index()
sales_trend['Order_Date'] = sales_trend['Order_Date'].dt.to_timestamp()
fig = px.line(sales_trend, x='Order_Date', y='Profit', title="Profit Trend")
fig.show()

In [42]:
# Regions Profit
region_profit = df2.groupby('Region')['Profit'].sum().reset_index().sort_values(by="Profit", ascending=True)
pivot=pd.pivot_table( df2,values='Profit',index='Year', columns='Region',aggfunc='sum')
fig = px.bar( region_profit, x="Profit",y="Region",orientation="h", text="Profit",color="Profit", color_continuous_scale="Blues",title="Profit by Region")


print(pivot)
fig.show()

Region  Bangalore      Delhi  Hyderabad    Kolkata     Mumbai       Pune
Year
2023     43965.24   36398.81   40931.73   44612.93   61987.06   40054.16
2024    307457.70  322401.04  302388.32  333575.29  320155.23  293985.25
2025    365777.98  315319.33  269732.14  273875.27  276772.39  287324.11

In [43]:
# Profit based on Gender Category
gender_profit = df2.groupby('Gender_Category')['Profit'].sum().reset_index().sort_values(by="Profit", ascending=True)
fig = px.bar(gender_profit,x="Profit",y="Gender_Category",orientation="h",text="Profit",color="Profit",color_continuous_scale="Purples",title="Profit on Gender based")
fig.show()

In [44]:
# Profit besed on Product Line
product_line_profit= df2.groupby('Product_Line')['Profit'].sum().reset_index().sort_values(by="Profit", ascending=True)
pivot=pd.pivot_table(df2,values='Profit',index='Year',columns='Product_Line',aggfunc='sum')
fig = px.bar( product_line_profit, x="Profit", y="Product_Line", orientation="h", text="Profit",color="Profit", color_continuous_scale="Blues",title="Profit by Product Line")
print(pivot)
fig.show()

Product_Line  Basketball  Lifestyle    Running     Soccer   Training
Year
2023            53905.70   68581.87   31550.76   54345.00   59566.60
2024           359495.67  358262.00  378013.73  391522.08  392669.35
2025           374381.48  356003.75  355506.17  320187.28  382722.54

In [45]:
# Top 10 products by profit
top_products_profit = (df2.groupby("Product_Name") .agg({"Profit":"sum"}).reset_index().sort_values(by="Profit", ascending=True).head(10))
fig = px.bar(top_products_profit,x="Profit",y="Product_Name",orientation="h",color="Profit",title="Top 10 Products by Profit",labels={"Profit":"Total Profit","Product_Name":"Product Name"})
fig.show()

In [47]:
# Sales Channel
channel_counts = df2['Sales_Channel'].value_counts().reset_index()
channel_counts.columns = ['Sales_Channel', 'Count']
# 
fig = px.bar( channel_counts, x="Sales_Channel",y="Count",text="Count",color="Sales_Channel",title="Sales Distribution by Channel")
fig.show()

In [48]:
# which sales channel has the most sales?During weekend or working days?
channel_counts = df2.groupby([ 'Sales_Channel','Day_Type']).size().reset_index(name='Count')

fig = px.bar(channel_counts, x='Day_Type',y='Count',color='Sales_Channel',barmode='group', text='Count',title="Sales Channel During weekend/working days")
fig.show()

In [49]:
# Sales by year, month, and channel
sales_trend = df.groupby([df['Order_Date'].dt.to_period('M'), 'Sales_Channel'])['Profit'].sum().reset_index()
sales_trend['Order_Date'] = sales_trend['Order_Date'].dt.to_timestamp()
sales_trend['Year'] = sales_trend['Order_Date'].dt.year
fig = px.line(sales_trend,x='Order_Date',y='Profit',color='Sales_Channel',facet_col='Year',title='Online vs Retail Sales Trends by Year')
fig.show()

In [50]:
# Sales by Gender Category
gender_sales = df2.groupby('Gender_Category')['Units_Sold'].sum().reset_index()
fig = px.pie( gender_sales,names="Gender_Category",values="Units_Sold",title="Sales by Gender Category",color="Gender_Category",)


fig.show()

In [51]:
#Top 10 products sales
top_products_sales = ( df2.groupby("Product_Name").agg({"Units_Sold":"sum"}).reset_index().sort_values(by="Units_Sold", ascending=True).head(10))

# --- Horizontal bar chart ---
fig = px.bar(top_products_sales,x="Units_Sold",y="Product_Name",orientation="h",color="Units_Sold",title="Top 10 Products by Units Sold",labels={"Profit":"Total Units Sold","Product_Name":"Product Name"})

fig.show()

In [52]:
# Total units sold for each size
size_units = df2.groupby('Size')['Units_Sold'].sum().reset_index().sort_values(by='Units_Sold', ascending=False)
fig = px.bar(size_units, x="Size", y="Units_Sold",text="Units_Sold", color="Units_Sold",color_continuous_scale="Blues",title="Total Units Sold For each Size")

print(size_units)
fig.show()

       Size  Units_Sold
7         L         942
9   UNKNOWN         925
10       XL         897
8         M         881
4         7         164
0        10         136
1        11         132
6         9         126
5         8         114
2        12         107
3         6         100

In [53]:
#Regional Performance
if 'Region' in df.columns:
    region_sales = df.groupby("Region")["Profit"].sum().sort_values(ascending=False).reset_index()
    print("Profit by Region:\n", region_sales)

    fig = px.bar(region_sales, x="Region", y="Profit", title="Profit by Region")
    fig.show()

Profit by Region:
       Region     Profit
0  Bangalore  717200.92
1      Delhi  674119.18
2     Mumbai  658914.68
3    Kolkata  652063.49
4       Pune  621363.52
5  Hyderabad  613052.19

In [55]:
# Customer Behavior..
fig = px.histogram(df, x="Units_Sold", nbins=30, title="Basket Size Distribution")
fig.show()

In [56]:
# Units_Sold vs Profit Relationship
fig = px.scatter(df2, x="Units_Sold",y="Profit",color="Product_Line", size="Units_Sold", hover_data=["Product_Line","Region","Size"],title="Units Sold vs Profit Relationship by Product Line")

fig.show()

In [58]:
#  Size Percentages
gender_counts = (
    df2.groupby("Size")
       .agg({"Units_Sold":"sum"})
       .reset_index()
)

# --- Calculate percentages ---
gender_counts["Percentage"] = (
    gender_counts["Units_Sold"] / gender_counts["Units_Sold"].sum() * 100
)

# --- Pie chart ---
fig = px.pie(
    gender_counts,
    names="Size",
    values="Percentage",
    title="Product Size Percentages",
    color="Size"
)

fig.show()